import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About | Next App',
  description: 'Generated by create next app',
}

const About = () => {
  return <h3>Select subitem</h3>
}

export default About